[project]
name = "dataops-bc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.1",
    "polars>=1.32.2",
    "pyarrow>=21.0.0",
]

[dependency-groups]
dev = [
    "notebook>=7.4.5",
    
]