services:

    postgres:
      image: postgres:17-alpine 
      hostname: postgres
      container_name: postgres
      ports:
        - ${POSTGRES_PORT_2}:5432
      command: ["postgres", "-c", "wal_level=logical", "-c", "max_replication_slots=10", "-c", "max_wal_senders=10"]
      volumes:
        - postgres-data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s