name: Backup & Restore

on:
  workflow_dispatch:
    inputs:
      restore:
        description: 'Run restore job?'
        required: false
        default: 'false'
  schedule:
    - cron: '*/3 * * * *'   # Every 3 minutes

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run backup script
        run: |
          chmod +x ./init/backup.sh
          ./init/backup.sh
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BACKUP_PATH: ./backups/

      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: db-backup-${{ github.run_id }}
          path: ./backups/

  restore:
    runs-on: ubuntu-latest
    needs: backup
    if: github.event.inputs.restore == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Download latest backup
        uses: actions/download-artifact@v4
        with:
          name: db-backup-${{ github.run_id }}

      - name: Run restore script
        run: |
          chmod +x ./init/restore.sh
          ./init/restore.sh
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BACKUP_PATH: ./backups/
