name: Postgres Backup

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *' # Every 2 minutes

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Ensure Docker is available
      - name: Check Docker
        run: docker info

      # 3️⃣ Make cron_job_runner.sh executable
      - name: Set script permissions
        run: chmod +x ./cron_job_runner.sh

      # 4️⃣ Run the backup script
      - name: Run Postgres backup
        env:
          HOST_BACKUP_DIR: ${{ github.workspace }}/postgres_backups
          DB_NAME: bootcamp_db
          DB_USER: bootcamp_admin
        run: ./cron_job_runner.sh

      # 5️⃣ Upload backups as artifact
      - name: Upload backup files
        uses: actions/upload-artifact@v4
        with:
          name: postgres-backups
          path: ${{ github.workspace }}/postgres_backups
