name: Backup & Restore Database

on:
  workflow_dispatch:
    inputs:
      restore:
        description: 'Run restore job?'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

env:
  BACKUP_PATH: ./backups/
  DB_USER: bootcamp_admin
  DB_PASSWORD: secure_password
  DB_NAME: bootcamp_db
  DB_PORT: 5434
  
jobs:

  backup:

    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: $DB_USER
          POSTGRES_PASSWORD: DB_PASSWORD
          POSTGRES_DB: $DB_NAME
        ports:
          - $DB_PORT:5432
        options: >-
          --health-cmd="pg_isready -U $DB_USER -d $DB_NAME"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
      - name: Run backup script
        run: |
          chmod +x ./init/backup.sh
          ./init/backup.sh
        env:
          DATABASE_URL: postgres://bootcamp_admin:secure_password@localhost:5434/bootcamp_db
          BACKUP_PATH: ./backups/
      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: db-backup-${{ github.run_id }}
          path: ./backups/

  restore:

    runs-on: ubuntu-24.04

    needs: backup
    if: github.event.inputs.restore == 'true'
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: $DB_USER
          POSTGRES_PASSWORD: $DB_PASSWORD
          POSTGRES_DB: $DB_NAME
        ports:
          - $DB_PORT:5432
        options: >-
          --health-cmd="pg_isready -U $DB_USER -d $DB_NAME"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Download latest backup
        uses: actions/download-artifact@v4
        with:
          name: db-backup-${{ github.run_id }}
          path: ./backups/
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
      - name: Download latest backup
        uses: actions/download-artifact@v4
        with:
          name: db-backup-${{ github.run_id }}
          path: ./backups/
      - name: Verify latest backup checksum
        run: |
          echo "🔍 Verifying latest backup checksum..."
          CHECKSUM_FILE=$(ls -t ./backups/*.sha256 2>/dev/null | head -n1)
          if [[ -z "$CHECKSUM_FILE" ]]; then
            echo "❌ No checksum file found!"
            exit 1
          fi
          sha256sum -c "$CHECKSUM_FILE"
      - name: Run restore script
        run: |
          chmod +x ./init/restore.sh
          ./init/restore.sh
