
# Backup & Restore Automation Workflow
name: Backup & Restore

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' 
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Backup database
        run: ./cron_job_runner.sh
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BACKUP_PATH: postgres_backups/
