name: Backup & Restore Database

on:
  workflow_dispatch:
    inputs:
      restore:
        description: 'Run restore job?'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:

  backup:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: bootcamp_admin
          POSTGRES_PASSWORD: secure_password
          POSTGRES_DB: bootcamp_db
        ports:
          - 5434:5432
        options: >-
          --health-cmd="pg_isready -U bootcamp_admin -d bootcamp_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Run backup script
        run: |
          chmod +x ./init/backup.sh
          ./init/backup.sh
        env:
          DATABASE_URL: postgres://bootcamp_admin:secure_password@localhost:5434/bootcamp_db
          BACKUP_PATH: ./backups/

      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: db-backup-${{ github.run_id }}
          path: ./backups/

  restore:
    runs-on: ubuntu-latest
    needs: backup
    if: github.event.inputs.restore == 'true'

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: bootcamp_admin
          POSTGRES_PASSWORD: secure_password
          POSTGRES_DB: bootcamp_db
        ports:
          - 5434:5432
        options: >-
          --health-cmd="pg_isready -U bootcamp_admin -d bootcamp_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Download latest backup
        uses: actions/download-artifact@v4
        with:
          name: db-backup-${{ github.run_id }}
          path: ./backups/

      - name: Verify latest backup checksum
        run: |
          echo "🔍 Verifying latest backup checksum..."
          CHECKSUM_FILE=$(ls -t ./backups/*.sha256 2>/dev/null | head -n1)
          if [[ -z "$CHECKSUM_FILE" ]]; then
            echo "❌ No checksum file found!"
            exit 1
          fi
          sha256sum -c "$CHECKSUM_FILE"

      - name: Run restore script
        run: |
          chmod +x ./init/restore.sh
          ./init/restore.sh
        env:
          DATABASE_URL: postgres://bootcamp_admin:secure_password@localhost:5434/bootcamp_db
          BACKUP_PATH: ./backups/
