
# Backup & Restore Automation Workflow
name: Backup & Restore

on:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *' 
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Backup database
        run: ./home/saadkh/dataops-bc/init/backup.sh
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BACKUP_PATH: backups/
